export const GET_ALL_PENDING_REQUEST_FOR_MANAGER =
  "GET_ALL_PENDING_REQUEST_FOR_MANAGER";
export const GET_ALL_ACCEPTED_REQUEST_FOR_MANAGER =
  "GET_ALL_ACCEPTED_REQUEST_FOR_MANAGER";
export const GET_ALL_DECLINED_REQUEST_FOR_MANAGER =
  "GET_ALL_DECLINED_REQUEST_FOR_MANAGER";
export const ACCEPT_REQUEST_FOR_MANAGER = "ACCEPT_REQUEST_FOR_MANAGER";
export const DECLINE_REQUEST_FOR_MANAGER = "DECLINE_REQUEST_FOR_MANAGER";
