export const GET_ALL_PENDING_REQUEST_FOR_STOREHEAD =
  "GET_ALL_PENDING_REQUEST_FOR_STOREHEAD";
export const GET_ALL_ACCEPTED_REQUEST_FOR_STOREHEAD =
  "GET_ALL_ACCEPTED_REQUEST_FOR_STOREHEAD";
export const GET_ALL_DECLINED_REQUEST_FOR_STOREHEAD =
  "GET_ALL_DECLINED_REQUEST_FOR_STOREHEAD";
