export const GET_ALL_PENDING_REQUEST_FOR_STOREKEEPER =
  "GET_ALL_PENDING_REQUEST_FOR_STOREKEEPER";
export const GET_ALL_ACCEPTED_REQUEST_FOR_STOREKEPPER =
  "GET_ALL_ACCEPTED_REQUEST_FOR_STOREKEPPER";
